import type { Department } from "./types";

export const departmentsB: Department[] = [
  {
    slug: "paediatrics",
    name: "Paediatrics",
    icon: "baby",
    tagline: "Gentle care for little patients",
    cardDescription:
      "Newborn care, child growth monitoring, vaccinations and treatment of childhood illnesses from doctors who know how to put children at ease.",
    overview: [
      "Children are not small adults — they need doctors who can examine, communicate and reassure in ways that work for young patients and anxious parents alike. Our paediatric team provides everyday illness care, growth and development monitoring, and newborn support in a child-friendly environment.",
      "We partner closely with parents: clear guidance on nutrition, sleep, development and vaccination schedules means families leave each visit knowing exactly what to expect as their child grows.",
    ],
    conditions: [
      "Newborn care and jaundice",
      "Childhood fevers and infections",
      "Growth and development concerns",
      "Nutritional deficiencies",
      "Asthma and allergies in children",
      "Vaccination-preventable diseases",
      "Adolescent health guidance",
    ],
    treatments: [
      "Well-baby and well-child clinics",
      "Complete immunisation services (IAP schedule)",
      "Growth and development assessment",
      "Childhood asthma and allergy management",
      "Newborn examination and feeding support",
      "Paediatric OPD for acute illnesses",
      "Parenting and nutrition counselling",
    ],
    highlights: [
      "Child-friendly consultation rooms that reduce fear",
      "On-schedule vaccination reminders for every registered child",
      "Newborn support programme for first-time parents",
    ],
  },
  {
    slug: "ent",
    name: "ENT",
    shortName: "ENT",
    icon: "ear",
    tagline: "Hear, breathe and speak better",
    cardDescription:
      "Specialist care for ear infections, sinus problems, tonsillitis, hearing issues, voice disorders and head-neck conditions for all ages.",
    overview: [
      "Ear, nose and throat problems affect daily life quietly — disturbed sleep, repeated infections, hearing difficulty and constant congestion. Our ENT specialists combine detailed endoscopic examination with modern diagnostics to find the real cause and treat it effectively.",
      "From a child's repeated tonsillitis to an adult's snoring or an elder's hearing loss, we provide clear treatment pathways — medical management first, and precise day-care surgical procedures when they are genuinely needed.",
    ],
    conditions: [
      "Recurrent ear infections and discharge",
      "Sinusitis and nasal allergies",
      "Tonsillitis and adenoid problems",
      "Hearing loss and ear wax disorders",
      "Vertigo and balance problems",
      "Snoring and sleep apnoea evaluation",
      "Voice and swallowing disorders",
    ],
    treatments: [
      "Diagnostic nasal and ear endoscopy",
      "Audiometry (hearing testing)",
      "Medical management of sinus and allergy disease",
      "Tonsillectomy and adenoidectomy",
      "Ear drum repair and minor ear procedures",
      "Foreign body removal (ear, nose, throat)",
      "Vertigo evaluation and repositioning manoeuvres",
    ],
    highlights: [
      "Endoscopy-based diagnosis during the first visit",
      "Audiometry available in-house",
      "Day-care ENT surgery with rapid discharge",
    ],
  },
  {
    slug: "dermatology",
    name: "Dermatology",
    icon: "sparkles",
    tagline: "Healthy skin, hair and nails",
    cardDescription:
      "Medical treatment for acne, pigmentation, hair loss, eczema, psoriasis and allergies — with honest, realistic treatment plans.",
    overview: [
      "Skin conditions affect confidence as much as comfort. Our dermatology team believes in honest dermatology: accurate diagnosis, realistic expectations and treatment plans that fit each patient's skin type, lifestyle and budget.",
      "We treat the full range of medical skin, hair and nail conditions — from teenage acne and hair fall to eczema, psoriasis and pigmentation — supported by patch testing and diagnostic procedures where required.",
    ],
    conditions: [
      "Acne and acne scars",
      "Hair fall and scalp disorders",
      "Eczema and dermatitis",
      "Psoriasis",
      "Pigmentation and melasma",
      "Fungal and bacterial skin infections",
      "Drug allergies and urticaria (hives)",
    ],
    treatments: [
      "Dermatological consultation and skin analysis",
      "Patch testing for contact allergies",
      "Medical acne and pigmentation programmes",
      "Hair loss evaluation and treatment",
      "Chemical peels for indicated conditions",
      "Cryotherapy and minor procedures",
      "Skin cancer screening and mole checks",
    ],
    highlights: [
      "Evidence-based, treatment-first approach — no unnecessary procedures",
      "Plans tailored to Indian skin types",
      "Clear written skincare routines patients can actually follow",
    ],
  },
  {
    slug: "urology",
    name: "Urology",
    icon: "droplets",
    tagline: "Discreet, expert urinary care",
    cardDescription:
      "Kidney stones, urinary infections, prostate problems and male reproductive health — treated with sensitivity and modern techniques.",
    overview: [
      "Urinary and kidney problems are common and very treatable, yet patients often delay seeking help out of embarrassment. Our urology team provides discreet, judgement-free consultations and clear explanations so patients can address problems early — when they are easiest to treat.",
      "Kidney stones, prostate enlargement, urinary infections and bladder concerns are evaluated with ultrasound imaging and lab support under one roof, and treated with medical or minimally invasive approaches as appropriate.",
    ],
    conditions: [
      "Kidney and ureteric stones",
      "Urinary tract infections (men and women)",
      "Prostate enlargement (BPH)",
      "Bladder control problems",
      "Blood in urine (haematuria)",
      "Male infertility and sexual health",
      "Paediatric urology concerns",
    ],
    treatments: [
      "Ultrasound KUB and urological imaging",
      "Medical expulsive therapy for stones",
      "Endoscopic stone procedures (URS/cystoscopy)",
      "Prostate evaluation and medical management",
      "Uroflowmetry and bladder assessment",
      "Male sexual health clinics",
      "Preventive kidney health reviews",
    ],
    highlights: [
      "Same-visit ultrasound for stone and prostate evaluation",
      "Minimally invasive techniques wherever possible",
      "Absolute confidentiality in every consultation",
    ],
  },
  {
    slug: "pulmonology",
    name: "Pulmonology",
    icon: "wind",
    tagline: "Breathing easier, living fuller",
    cardDescription:
      "Asthma, COPD, tuberculosis, sleep apnoea and chronic cough — structured respiratory care with modern lung function testing.",
    overview: [
      "Breathlessness and chronic cough deserve careful investigation, not assumptions. Our pulmonology team diagnoses the true cause of respiratory symptoms using lung function testing, imaging and structured clinical assessment.",
      "Long-term conditions like asthma and COPD are managed with written action plans, inhaler technique training and scheduled reviews — because good respiratory care is about preventing flare-ups, not just treating them.",
    ],
    conditions: [
      "Asthma and allergic airway disease",
      "COPD and smoker's lung",
      "Persistent and chronic cough",
      "Tuberculosis diagnosis and follow-up",
      "Obstructive sleep apnoea",
      "Pneumonia and respiratory infections",
      "Occupational lung disease",
    ],
    treatments: [
      "Spirometry (lung function testing)",
      "Inhaler technique training and review",
      "Sleep apnoea screening",
      "Chest X-ray and CT imaging coordination",
      "TB evaluation and DOTS-linked care",
      "Smoking cessation support",
      "Allergy evaluation",
    ],
    highlights: [
      "Spirometry available on-site for objective diagnosis",
      "Written asthma/COPD action plans for every patient",
      " Inhaler technique checked at every review",
    ],
  },
  {
    slug: "radiology",
    name: "Radiology & Imaging",
    icon: "scan-line",
    tagline: "Answers you can see",
    cardDescription:
      "Digital X-ray, ultrasound, CT and lab services with fast, accurate reporting — the diagnostic backbone of every department in the hospital.",
    overview: [
      "Accurate diagnosis is the foundation of good treatment. Our radiology and imaging centre supports every department with digital X-ray, ultrasound, CT imaging and a fully equipped clinical laboratory, working to turnaround times that keep care moving.",
      "Reports are shared with patients and referring doctors promptly, and our radiologists are available for consultation so imaging findings translate into clear next steps rather than anxiety.",
    ],
    conditions: [
      "Routine and emergency imaging needs",
      "Abdominal and obstetric ultrasound",
      "Chest and skeletal X-ray evaluation",
      "Stroke, trauma and oncology CT imaging",
      "Laboratory-based disease screening",
      "Pre-operative fitness testing",
      "Preventive health check panels",
    ],
    treatments: [
      "Digital X-ray",
      "Ultrasound and Doppler studies",
      "CT scanning",
      "Fully automated clinical laboratory",
      "ECG and TMT services",
      "Same-day reporting for most routine tests",
      "Digital reports accessible to patients and doctors",
    ],
    highlights: [
      "Most routine lab and X-ray reports the same day",
      "Radiologist consultation on every significant finding",
      "Emergency imaging prioritised around the clock",
    ],
  },
];
