import {
  HeartPulse,
  Bone,
  Brain,
  Stethoscope,
  Scissors,
  HeartHandshake,
  Baby,
  Ear,
  Sparkles,
  Droplets,
  Wind,
  ScanLine,
  Microscope,
  Siren,
  ShieldCheck,
  Activity,
  Ambulance,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  Building2,
  CalendarCheck,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Clock,
  Clock3,
  CreditCard,
  FileText,
  GraduationCap,
  Languages,
  Loader2,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Navigation,
  Phone,
  PhoneCall,
  Quote,
  Star,
  Users,
  UserRound,
  Heart,
  Pill,
  Syringe,
  Thermometer,
  X,
  BedDouble,
  Scan,
  TestTube2,
  ClipboardList,
  HandHeart,
  CircleCheck,
  BookOpenCheck,
  Car,
  BabyIcon,
  UserSearch,
  CalendarClock,
  Hospital,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  "heart-pulse": HeartPulse,
  bone: Bone,
  brain: Brain,
  stethoscope: Stethoscope,
  scissors: Scissors,
  "heart-handshake": HeartHandshake,
  baby: Baby,
  ear: Ear,
  sparkles: Sparkles,
  droplets: Droplets,
  wind: Wind,
  "scan-line": ScanLine,
  microscope: Microscope,
  siren: Siren,
  "shield-check": ShieldCheck,
  activity: Activity,
  ambulance: Ambulance,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  award: Award,
  "badge-check": BadgeCheck,
  building: Building2,
  "calendar-check": CalendarCheck,
  "check-circle": CheckCircle2,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  clock: Clock,
  "clock-3": Clock3,
  "credit-card": CreditCard,
  "file-text": FileText,
  "graduation-cap": GraduationCap,
  languages: Languages,
  loader: Loader2,
  mail: Mail,
  "map-pin": MapPin,
  menu: Menu,
  whatsapp: MessageCircle,
  navigation: Navigation,
  phone: Phone,
  "phone-call": PhoneCall,
  quote: Quote,
  star: Star,
  users: Users,
  user: UserRound,
  heart: Heart,
  pill: Pill,
  syringe: Syringe,
  thermometer: Thermometer,
  x: X,
  bed: BedDouble,
  scan: Scan,
  "test-tube": TestTube2,
  clipboard: ClipboardList,
  "hand-heart": HandHeart,
  "circle-check": CircleCheck,
  "book-open": BookOpenCheck,
  car: Car,
  child: BabyIcon,
  "user-search": UserSearch,
  "calendar-clock": CalendarClock,
  hospital: Hospital,
};

export function CIcon({
  name,
  className,
  strokeWidth = 1.8,
}: {
  name: string;
  className?: string;
  strokeWidth?: number;
}) {
  const Icon = icons[name] ?? Activity;
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden="true" />;
}
